apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: workshop
spec:
  selector:
    app: elearning-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
